theme: minima

title: modmail.js
description: A guide made by the contributors of modmail.js for its users.
author: Imagine A Template  

minima:
  skin: dark
header_pages:
  - README.md
  - plugins.md
show_excerpts: false



plugins:
 - jekyll-seo-tag
