theme: minima



title: modmail.js
description: A guide made by the contributors of modmail.js for its users.
author: Imagine A Template  

url: https://modmail.js.org

social_links:
    github:  BotStudios
 
header_pages:
- README.md
- plugins.md

show_excerpts: false

mastodon:
    - username: npmjs
      instance: npmjs.com/modmail.js
     

