theme: just-the-docs
title: modmail.js
description: Documentation For Modmail.js
search_enabled: true
footer_content: Copyright &copy; by <a href="https://github.com/botstudios">Bot Studios</a>. A guide made by the contributors of modmail.js for its users.
url: "https://modmail.js.org/docs"
heading_anchors: true
nav_sort: case_sensitive
permalink: pretty
color_scheme: nil

aux_links:
  Guide: "//modmail.js.org"
  Repository: "//github.com/botstudios/modmail.js"
  npmjs: "//npmjs.com/package/modmail.js"
  
plugins:
  - jekyll-seo-tag
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  
remote_theme: pmarsceill/just-the-docs
